# Generated by Django 5.1.4 on 2024-12-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.CharField(choices=[('IN', 'Indian'), ('CH', 'Chinese'), ('MX', 'Mexican'), ('IT', 'Italian'), ('FF', 'Fastfood'), ('OT', 'Other')], default='', max_length=2),
            preserve_default=False,
        ),
    ]
